POST http://localhost:9555/prices/checkout
Content-Type: application/x-www-form-urlencoded

itemName=C&&rule=5 for 100
###




###
GET http://localhost:9555/prices
Accept: application/json

###

POST http://localhost:9555/prices/total
Content-Type: application/x-www-form-urlencoded

items=C C C C C C A A A A

###

