POST http://localhost:9555/prices/checkout


itemName=C&&rule=5 for 100
###




###
GET http://localhost:9555/prices
Accept: application/json

###

POST http://localhost:9555/prices/total


C C C C C C A A A A

###

